Custom commands
momentum-mod/discord-bot pull request #110
Opened 2022-05-29 16:27 UTC by BIRD311

custom commands can be added with "/custom add" or rightclick on a message -> Apps -> add as custom command
commands can be executed with "/say"
/custom, /say and the context menu permissions can be adjusted separately in the server settings
I order for autocompletion to work after changing the list (adding, removing, renaming) I had to call refresh which makes slashcommands not responsive and they tell you "This command is outdated, please try again in a few minutes". I usually just click on a different channel and back and they work again. The other way I found to get to choiceprovider to refresh is to reconnect the bot but this seems even uglier.
Commands are saved to the config file so right now they would only stick around until the image gets rebuilt (haven't tested this)
The permission check on the contextmenu commands didn't work and I fix this here too. Had to add separate attributes because there is no other base type or interface. They also have different exception handling than slashcommands so I have to touch this again after PR 109 gets merged.

2022-05-29 22:06 UTC, tsa96 requested changes
Nice work!

I'm tempted to ask you to improve formatting in some other places (especially inserting spaces between `if(foo)`) but it's not the end of the world.

You should definitely switch to registering guild only commands. I don't mind if you just do the method registering an empty command module globally in this branch, and I'll then remove that once I've run it on the live bot.

If you could look into the slowness with `RefreshCommands` that'd be great, as we discussed in Discord.

2022-05-29 22:06 UTC, tsa96 commented on MomentumDiscordBot/Commands/Moderator/ModeratorCustomModule.cs
> +                    + "' created from message: " + message.JumpLink.ToString()
Should be indented

2022-05-29 22:06 UTC, tsa96 commented on MomentumDiscordBot/Commands/Moderator/ModeratorCustomModule.cs
> +        , [Option("name", "name of the new command")] string name
Formatting here I just can't live with, sorry, please put the commas on the above lines!

Same in a few other places.

2022-05-29 22:06 UTC, tsa96 commented on MomentumDiscordBot/Services/SlashCommandService.cs
> +using System.Collections.Concurrent;
These don't look like they're being used

2022-05-29 22:06 UTC, tsa96 commented on MomentumDiscordBot/Models/Configuration.cs
> +using System.Collections.Generic;
Unused

2022-05-29 22:06 UTC, tsa96 commented on MomentumDiscordBot/Commands/Moderator/ModeratorCustomModule.cs
> +            CustomCommand command;
This is unused, no?

2022-05-29 22:06 UTC, tsa96 commented on MomentumDiscordBot/Commands/General/GeneralModule.cs
> +﻿using System;
Unused

2022-05-29 22:06 UTC, tsa96 commented on MomentumDiscordBot/Services/SlashCommandService.cs
> +        }
I'm not a fan of how this is essentially a duplicate of `_commands_SlashCommandErrored`. Could you create a method that handles both, and have each handler call it?

2022-05-29 22:06 UTC, tsa96 commented on MomentumDiscordBot/Utilities/DiscordExtensions.cs
> +            if (!(user is DiscordMember member))
`if (user is not ...`

2022-05-29 22:06 UTC, tsa96 commented on MomentumDiscordBot/Commands/General/GeneralModule.cs
> +        [SlashCommand("say", "executes a custom command")]
Could we lock this behind the "Trusted" role?

2022-05-29 22:27 UTC, tsa96 requested changes

2022-05-29 22:27 UTC, tsa96 commented on MomentumDiscordBot/Commands/ChoiceProvider/CustomCommandChoiceProvider.cs
> +            return Task.FromResult(choices.AsEnumerable());
Can just construct an Enumerable here, and use Linq:
```C#
var choices = commands.Select(command => new DiscordApplicationCommandOptionChoice(command, command));
return Task.FromResult(choices);
```

2022-05-30 10:46 UTC, tsa96 commented on MomentumDiscordBot/Commands/Moderator/ModeratorCustomModule.cs
> +                Title = "Commands:",
Colon looks a bit weird here, can just remove it. And maybe "Info Commands" is better.

2022-05-30 10:48 UTC, tsa96 commented
Reminder that we should close #105 once this is in

2022-05-30 14:16 UTC, BIRD311 commented on MomentumDiscordBot/Commands/Moderator/ModeratorCustomModule.cs
> +            CustomCommand command;
I was about to say "sure but it needs the argument" but apparently we can discard outs now. I have learned something today :).

2022-05-30 15:14 UTC, BIRD311 commented on MomentumDiscordBot/Services/SlashCommandService.cs
> +        }
I was always thinking "I have to change this after 109 anyway" so I didn't look at this again but yes I really dislike redundant code too. Changed it now but even though everything looks the same there are no interfaces for this (again) so it didn't turn out very nice.

2022-05-30 15:16 UTC, BIRD311 commented on MomentumDiscordBot/Utilities/DiscordExtensions.cs
> +            if (!(user is DiscordMember member))
thats not my code I just moved it :)
changed now

2022-05-30 15:48 UTC, BIRD311 commented on MomentumDiscordBot/Commands/General/GeneralModule.cs
> +        [SlashCommand("say", "executes a custom command")]
Trusted is something the bot doesn't know yet and Graduated is the FAQ role right? Added trusted_id to the config and used it here. I just put the attribute on the GeneralModule now but if you want I can make a new base type and a "trusted" directory like admin and moderator have. Then the GeneralModule is empty and useless again and I can remove it.

2022-05-30 16:57 UTC, BIRD311 commented
I pushed the things you requested except "refresh slowness".
Messed with autoformatting a little bit but haven't found anything I like yet.

You can test again if you want or wait until I'm done with everything.

2022-05-30 22:32 UTC, tsa96 commented on MomentumDiscordBot/Commands/General/GeneralModule.cs
> +        [SlashCommand("say", "executes a custom command")]
The bot handles Trusted already - see UserTrustService.cs!

2022-05-30 22:33 UTC, tsa96 commented
Yeah all good, no rush. Looking into the RefreshCommands stuff some more would be great, though if it goes nowhere let me know, maybe we can just put up with the slowness.

2022-05-31 06:49 UTC, BIRD311 commented on MomentumDiscordBot/Commands/General/GeneralModule.cs
> +        [SlashCommand("say", "executes a custom command")]
oh I see .. "MediaVerifiedRoleId" .. thanks

2022-06-03 16:35 UTC, tsa96 commented on MomentumDiscordBot/Commands/Moderator/ModeratorCustomModule.cs
> +            int pages = (int)Math.Ceiling((double)Config.CustomCommands.Count() / itemsPerPage);
You can actually use the `.Count` *property* here rather than the `.Count()` *method*. (I'm cheating - Rider analysis pointed this out)

2022-06-03 16:37 UTC, tsa96 commented
Great, I'm happy with this. The `.Count` thing is so incredibly minor we can just leave it.

2022-06-03 16:37 UTC, tsa96 approved these changes

2022-06-03 16:38 UTC, merged