/custom edit and video embed
momentum-mod/discord-bot pull request #114
Opened 2022-06-10 16:20 UTC by BIRD311

As discussed with fingerprince "add as custom command" will ignore the video embeds now and I added /custom edit

"add as custom command" will take the embed content if you use it on a bot /say response. So you can basically copy commands (could be usefull if you break something with edit).
The value in "/custom edit" is optional and it will remove the value if left blank.
Ignoring the video embed (or rather, there shouldn't be one in the first place or you get the url in the message twice) means you also have to add the thumbnail.
I'm sure you can break something with bad urls but since this is a moderator command I didn't check too much.

2022-06-10 22:54 UTC, tsa96 requested changes
creationTimestamp throws an unhandled exception if the timestamp isn't valid, that should be caught. Though it doesn't seem like a very useful property anyway (if anything I just get confused over what it does, and I can't see us ever caring about when the command is registered), I think it'll be best to just remove that.

2022-06-10 22:54 UTC, tsa96 commented on MomentumDiscordBot/Commands/General/GeneralModule.cs
> +                        Url = command.ThumbnailUrl.ToString(),
ToString is redundant

2022-06-10 22:54 UTC, tsa96 commented on MomentumDiscordBot/Commands/General/GeneralModule.cs
> +                    message.AddComponents(new DiscordLinkButtonComponent(command.ButtonUrl.ToString(), command.ButtonLabel ?? "link"));
Another redundant ToString

2022-06-10 22:54 UTC, tsa96 commented on MomentumDiscordBot/Commands/Autocomplete/CustomCommandAutoCompleteProvider.cs
> +            var choices = properties.Take(25).Select(poperty => new DiscordApplicationCommandOptionChoice(poperty.Name, poperty.Name));
Typo in `popertry`. Doesn't really matter, but may as well change it if we're fixing up some other stuff.

2022-06-10 22:54 UTC, tsa96 commented on MomentumDiscordBot/Commands/Moderator/ModeratorCustomModule.cs
> +                    var embed = message.Embeds.First();
I don't think it's correct practice to use LINQ here where we can just use an index.
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1826

2022-06-11 09:18 UTC, BIRD311 commented on MomentumDiscordBot/Commands/Moderator/ModeratorCustomModule.cs
> +                    var embed = message.Embeds.First();
Did you IDE give you a warning here? There are multiple instances where First() is used like this in the code so I should probably change all of them?

2022-06-11 16:02 UTC, tsa96 commented on MomentumDiscordBot/Commands/Moderator/ModeratorCustomModule.cs
> +                    var embed = message.Embeds.First();
Yeah, though I was only reading through your new code. If it's happening in other places it's not a big deal, I've been trying to only flag stuff I've noticed in new code, the same stuff is used in other places then we can let it slide, there's lots of small issues that linters spot in the code already that we don't need to worry about.

2022-06-11 16:22 UTC, BIRD311 commented on MomentumDiscordBot/Commands/Moderator/ModeratorCustomModule.cs
> +                    var embed = message.Embeds.First();
ok I'll change this and maybe I can clean up the rest of the code later

2022-06-17 05:33 UTC, tsa96 approved these changes
This is all working well, nice job!

2022-06-17 05:33 UTC, merged